#!/usr/bin/env bash
# scripts/dev.sh — M5.9.2 developer-loop orchestrator.
#
# Runs:
#   • the dblock daemon on an unprivileged port (default 18099 / DNS 15353)
#     from a dedicated data dir (default ~/tmp/dblock-dev)
#   • vite dev on port 5173 (default), proxying /api and /metrics to the
#     daemon (configured in web/vite.config.ts).
#
# Edit a .vue file → Vite HMR reloads the module in the browser without
# rebuilding the Go binary.
#
# Ctrl-C cleanly stops both processes (SIGTERM → wait → done).
#
# Override knobs (all optional):
#   DBLOCK_DEV_PORT     management API port           default 18099
#   DBLOCK_DEV_DIR      data dir + config + log root  default ~/tmp/dblock-dev
#   DBLOCK_DEV_DNS_PORT DNS listen port (unprivileged)default 15353
#   VITE_DEV_PORT       vite dev port                 default 5173

set -euo pipefail

# ---------- config ----------

DBLOCK_DEV_PORT="${DBLOCK_DEV_PORT:-18099}"
DBLOCK_DEV_DNS_PORT="${DBLOCK_DEV_DNS_PORT:-15353}"
DBLOCK_DEV_DIR="${DBLOCK_DEV_DIR:-$HOME/tmp/dblock-dev}"
VITE_DEV_PORT="${VITE_DEV_PORT:-5173}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DBLOCK_BIN="$REPO_ROOT/apps/dblock/dblock"
DBLOCK_LOG="$DBLOCK_DEV_DIR/dblock.log"
DBLOCK_CFG="$DBLOCK_DEV_DIR/config.yaml"

# ---------- helpers ----------

log()  { printf '[make dev] %s\n' "$*" >&2; }
warn() { printf '[make dev] WARN: %s\n' "$*" >&2; }
die()  { printf '[make dev] ERROR: %s\n' "$*" >&2; exit 1; }

DBLOCK_PID=""
VITE_PID=""

# kill_tree sends a signal to a PID and every descendant. npm exec wraps
# vite under a node sub-process that doesn't always forward TERM cleanly,
# so we walk the tree ourselves to guarantee no zombies.
kill_tree() {
  local sig="$1" pid="$2"
  [ -z "$pid" ] && return 0
  kill -0 "$pid" 2>/dev/null || return 0
  # Children first (post-order), then the parent.
  local kids
  kids=$(pgrep -P "$pid" 2>/dev/null || true)
  for k in $kids; do
    kill_tree "$sig" "$k"
  done
  kill -"$sig" "$pid" 2>/dev/null || true
}

cleanup() {
  trap - INT TERM EXIT
  log "shutting down…"
  kill_tree TERM "$VITE_PID"
  kill_tree TERM "$DBLOCK_PID"
  # Give the trees up to 5s to exit gracefully, then SIGKILL the holdouts.
  for _ in 1 2 3 4 5; do
    alive=0
    [ -n "$VITE_PID" ]   && kill -0 "$VITE_PID"   2>/dev/null && alive=1
    [ -n "$DBLOCK_PID" ] && kill -0 "$DBLOCK_PID" 2>/dev/null && alive=1
    # Stray vite sub-processes (npm exec → sh → node) may outlive npm —
    # check by port too.
    if ss -ltn 2>/dev/null | grep -qE "127\\.0\\.0\\.1:$VITE_DEV_PORT\\b"; then
      alive=1
    fi
    [ "$alive" = 0 ] && break
    sleep 1
  done
  kill_tree KILL "$VITE_PID"
  kill_tree KILL "$DBLOCK_PID"
  # Last-resort sweep: anything still bound to our two known dev ports
  # gets a SIGKILL by PID (handles the rare npm-exec leak where a node
  # grandchild detached from its parent's tree).
  for port in "$VITE_DEV_PORT" "$DBLOCK_DEV_PORT"; do
    pids=$(ss -ltnp 2>/dev/null \
      | awk -v p=":$port" '$0 ~ p { print }' \
      | grep -oE 'pid=[0-9]+' | cut -d= -f2 | sort -u || true)
    for p in $pids; do
      kill -KILL "$p" 2>/dev/null || true
    done
  done
  log "stopped."
}
trap cleanup INT TERM EXIT

ensure_config() {
  mkdir -p "$DBLOCK_DEV_DIR"
  if [ -s "$DBLOCK_CFG" ]; then
    log "reusing existing config $DBLOCK_CFG"
    return
  fi
  log "writing minimal dev config to $DBLOCK_CFG"
  cat >"$DBLOCK_CFG" <<EOF
# Auto-generated by scripts/dev.sh — safe to edit; will not be overwritten.
node:
  id: dblock-dev
  raft_address: 127.0.0.1:17000
  api_address: 127.0.0.1:$DBLOCK_DEV_PORT
  data_dir: $DBLOCK_DEV_DIR
  dns:
    listen:
      port: $DBLOCK_DEV_DNS_PORT
      ipv4: true
      ipv6: false
EOF
}

ensure_binary() {
  if [ -x "$DBLOCK_BIN" ]; then
    log "reusing existing binary $DBLOCK_BIN"
    return
  fi
  log "dblock binary not found — building (one-time)…"
  (cd "$REPO_ROOT" && make build) || die "make build failed"
}

wait_for_api() {
  local url="http://127.0.0.1:$DBLOCK_DEV_PORT/api/v1/health"
  log "waiting for daemon on $url …"
  for _ in $(seq 1 20); do
    if curl -sf -o /dev/null -m 1 "$url" 2>/dev/null; then
      log "daemon up."
      return 0
    fi
    # /api/v1/health may legitimately return non-2xx (e.g. 401) before
    # auth is set up — treat any HTTP response as "TCP is listening".
    if curl -s -o /dev/null -m 1 -w '%{http_code}' "$url" 2>/dev/null | grep -qE '^[1-5][0-9][0-9]$'; then
      log "daemon up (responding with non-2xx, that's fine)."
      return 0
    fi
    sleep 0.5
  done
  die "daemon did not come up on :$DBLOCK_DEV_PORT within 10s — see $DBLOCK_LOG"
}

# ---------- run ----------

ensure_config
ensure_binary

log "starting dblock on :$DBLOCK_DEV_PORT (DNS :$DBLOCK_DEV_DNS_PORT, data $DBLOCK_DEV_DIR, log $DBLOCK_LOG)"
# Run from the data dir so any relative paths the daemon picks up land
# under it. Logs go to a file so vite's stdout stays readable.
(cd "$DBLOCK_DEV_DIR" && "$DBLOCK_BIN" --config "$DBLOCK_CFG") \
  >"$DBLOCK_LOG" 2>&1 &
DBLOCK_PID=$!

wait_for_api

log "starting vite dev on :$VITE_DEV_PORT (proxying /api + /metrics → :$DBLOCK_DEV_PORT)"
log "open http://127.0.0.1:$VITE_DEV_PORT/ in your browser"
log "(Ctrl-C to stop both processes)"

# Make sure npm deps are installed (idempotent).
if [ ! -d "$REPO_ROOT/web/node_modules" ]; then
  log "installing npm deps (one-time)…"
  (cd "$REPO_ROOT/web" && npm install --no-audit --no-fund) || die "npm install failed"
fi

# Run vite in the foreground so its coloured output reaches the operator's
# terminal, and so its exit code drives ours. Invoke the local binary
# directly (not via `npm exec`) so SIGTERM reaches node without going
# through an npm wrapper that doesn't always forward signals.
VITE_BIN="$REPO_ROOT/web/node_modules/.bin/vite"
if [ ! -x "$VITE_BIN" ]; then
  die "vite binary missing at $VITE_BIN — did npm install run?"
fi
(cd "$REPO_ROOT/web" && exec "$VITE_BIN" --port "$VITE_DEV_PORT" --strictPort) &
VITE_PID=$!

# Wait on vite specifically (the foreground UI process). When it exits,
# the EXIT trap cleans up dblock. Treat SIGINT/SIGTERM as a clean exit so
# `make dev` doesn't print a scary `Error 130` on Ctrl-C.
set +e
wait "$VITE_PID"
rc=$?
set -e
if [ "$rc" = 130 ] || [ "$rc" = 143 ]; then
  rc=0
fi
exit "$rc"
